export const LOGIN_USER = "LOGIN_USER";
export const REGISTER_USER = "REGISTER_USER";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const REGISTER_FAILURE = "REGISTER_FAILURE";
export const UPDATE_PROFILE_FIELD = "UPDATE_PROFILE_FIELD";
export const SAVE_PROFILE_DATA = "SAVE_PROFILE_DATA";
